export default {
  index: "/",
  dashboard: "/dashboard",
  myaccount: "/myaccount",
  deposits: "/deposits",
  educationalVideos: "/educational-videos",
  withdrawals: "/withdrawals",
  transactionHistory: "/transaction-history",
  downloadCenter: "/download-center",
  performance: "/performance",
  settings: "/settings",
  balanceOperations: "/balance-operations",
  closedTrades: "/closed-trades",
  completeProfile: "/complete-profile",
  editLeverage: "/edit-leverage",
  forgotPassword: "/forgot-password",
  // login: "/login",
  openTrades: "/open-trades",
  resetPassword: "/reset-password",
  transferFunds: "/transfer-funds",
  verifyEmail: "/verify-email",
  copyTrading: "/copy-trading",
  tradingTools: "/trading-tools",
  funds: "/funds",
  tradingCentral: "/trading-central",
  register: "/register",
};
