import aLinks from "./aLinks";

export const NEXT_PUBLIC_BASE_URL = process.env.NEXT_PUBLIC_BASE_URL;
export const NEXT_PUBLIC_BACKEND_API_URL =
  process.env.NEXT_PUBLIC_BACKEND_API_URL;
export const NEXT_PUBLIC_PRICE_FEED_WS = process.env.NEXT_PUBLIC_PRICE_FEED_WS;
export const NEXT_PUBLIC_CASHIER_URL = process.env.NEXT_PUBLIC_CASHIER_URL;

export const MT5_ACCOUNT_GRPOUPS = [
  { group: "stv\\BTC", currency: "BTC" },
  { group: "stv\\ETH", currency: "ETH" },
  { group: "stv\\TIO", currency: "TIO" },
  { group: "stv\\USD", currency: "USD" },
  { group: "stv\\EUR", currency: "EUR" },
  { group: "stv\\GBP", currency: "GBP" },
  { group: "stv\\CAD", currency: "CAD" },
  { group: "stv\\AUD", currency: "AUD" },
  { group: "stv\\USDT", currency: "UST" },
  { group: "stv\\CZK", currency: "CZK" },
  { group: "stv\\ZAR", currency: "ZAR" },
  { group: "stv\\BTC_2", currency: "BTC" },
  { group: "stv\\ETH_2", currency: "ETH" },
  { group: "stv\\TIO_2", currency: "TIO" },
  { group: "stv\\USD_2", currency: "USD" },
  { group: "stv\\EUR_2", currency: "EUR" },
  { group: "stv\\GBP_2", currency: "GBP" },
  { group: "stv\\CAD_2", currency: "CAD" },
  { group: "stv\\AUD_2", currency: "AUD" },
  { group: "stv\\USDT_2", currency: "UST" },
  { group: "stv\\CZK_2", currency: "CZK" },
  { group: "stv\\ZAR_2", currency: "ZAR" },
  { group: "stv\\BTC_5", currency: "BTC" },
  { group: "stv\\ETH_5", currency: "ETH" },
  { group: "stv\\TIO_5", currency: "TIO" },
  { group: "stv\\USD_5", currency: "USD" },
  { group: "stv\\EUR_5", currency: "EUR" },
  { group: "stv\\GBP_5", currency: "GBP" },
  { group: "stv\\CAD_5", currency: "CAD" },
  { group: "stv\\AUD_5", currency: "AUD" },
  { group: "stv\\USDT_5", currency: "UST" },
  { group: "stv\\CZK_5", currency: "CZK" },
  { group: "stv\\ZAR_5", currency: "ZAR" },
  { group: "stv\\BTC_Vip", currency: "BTC" },
  { group: "stv\\ETH_Vip", currency: "ETH" },
  { group: "stv\\TIO_Vip", currency: "TIO" },
  { group: "stv\\USD_Vip", currency: "USD" },
  { group: "stv\\EUR_Vip", currency: "EUR" },
  { group: "stv\\GBP_Vip", currency: "GBP" },
  { group: "stv\\CAD_Vip", currency: "CAD" },
  { group: "stv\\USDT_Vip", currency: "UST" },
  { group: "stv\\AUD_Vip", currency: "AUD" },
  { group: "stv\\CZK_Vip", currency: "CZK" },
  { group: "stv\\ZAR_Vip", currency: "ZAR" },
  { group: "stv\\BTC_Vipc", currency: "BTC" },
  { group: "stv\\ETH_Vipc", currency: "ETH" },
  { group: "stv\\TIO_Vipc", currency: "TIO" },
  { group: "stv\\USD_Vipc", currency: "USD" },
  { group: "stv\\EUR_Vipc", currency: "EUR" },
  { group: "stv\\GBP_Vipc", currency: "GBP" },
  { group: "stv\\CAD_Vipc", currency: "CAD" },
  { group: "stv\\USDT_Vipc", currency: "UST" },
  { group: "stv\\AUD_Vipc", currency: "AUD" },
  { group: "stv\\BTC10", currency: "BTC" },
  { group: "stv\\ETH10", currency: "ETH" },
  { group: "stv\\TIO10", currency: "TIO" },
  { group: "stv\\USD10", currency: "USD" },
  { group: "stv\\EUR10", currency: "EUR" },
  { group: "stv\\GBP10", currency: "GBP" },
  { group: "stv\\CAD10", currency: "CAD" },
  { group: "stv\\AUD10", currency: "AUD" },
  { group: "stv\\BTC11", currency: "BTC" },
  { group: "stv\\ETH11", currency: "ETH" },
  { group: "stv\\TIO11", currency: "TIO" },
  { group: "stv\\USD11", currency: "USD" },
  { group: "stv\\EUR11", currency: "EUR" },
  { group: "stv\\GBP11", currency: "GBP" },
  { group: "stv\\CAD11", currency: "CAD" },
  { group: "stv\\AUD11", currency: "AUD" },
  { group: "stv\\BTC16", currency: "BTC" },
  { group: "stv\\ETH16", currency: "ETH" },
  { group: "stv\\TIO16", currency: "TIO" },
  { group: "stv\\USD16", currency: "USD" },
  { group: "stv\\EUR16", currency: "EUR" },
  { group: "stv\\GBP16", currency: "GBP" },
  { group: "stv\\CAD16", currency: "CAD" },
  { group: "stv\\AUD16", currency: "AUD" },
  { group: "stv\\CADPAMM", currency: "CAD" },
  { group: "stv\\USDPAMM", currency: "USD" },
  { group: "stv\\GBPPAMM", currency: "GBP" },
  { group: "stv\\EURPAMM", currency: "EUR" },
  { group: "stv\\USDPAMM15", currency: "USD" },
  { group: "stv\\USD_BMF_Std", currency: "USD" },
  { group: "stv\\USD_BMF_V", currency: "USD" },
  { group: "stv\\USD_BMF_VB", currency: "USD" },
  { group: "stv\\EUR_BMF_VB", currency: "EUR" },
  { group: "stv\\EUR_BMF_Std", currency: "EUR" },
  { group: "stv\\EUR_BMF_V", currency: "EUR" },
  { group: "stv\\CZK_BMF_Std", currency: "CZK" },
  { group: "stv\\CZK_BMF_V", currency: "CZK" },
  { group: "stv\\CZK_BMF_VB", currency: "CZK" },
  { group: "stv\\ETH_BMF_Std", currency: "ETH" },
  { group: "stv\\ETH_BMF_V", currency: "ETH" },
  { group: "stv\\ETH_BMF_VB", currency: "ETH" },
  { group: "stv\\USD_TDX_Std", currency: "USD" },
  { group: "stv\\USD_TDX_V", currency: "USD" },
  { group: "stv\\USD_TDX_VB", currency: "USD" },
  { group: "stv\\EUR_TDX_Std", currency: "EUR" },
  { group: "stv\\EUR_TDX_V", currency: "EUR" },
  { group: "stv\\EUR_TDX_VB", currency: "EUR" },
  { group: "stv\\USD_BMF_CRY", currency: "USD" },
  { group: "stv\\EUR_BMF_CRY", currency: "EUR" },
  { group: "stv\\USD_8STD", currency: "USD" },
  { group: "stv\\USD_8V", currency: "USD" },
  { group: "stv\\USD_8Vip", currency: "USD" },
  { group: "stv\\USDTstd", currency: "UST" },
  { group: "stv\\USDmu5", currency: "USD" },
  { group: "stv\\USD_Vipmu", currency: "USD" },
  { group: "stv\\EUR20", currency: "EUR" },
  { group: "stv\\EURmu5", currency: "EUR" },
  { group: "stv\\EUR_8STD", currency: "EUR" },
  { group: "stv\\EUR_8V", currency: "EUR" },
  { group: "stv\\EUR_8Vip", currency: "EUR" },
  { group: "stv\\USD_micro", currency: "USM" },
  { group: "stv\\USD_MFX_Std", currency: "USD" },
  { group: "stv\\EUR8FXMU", currency: "EUR" },
  { group: "stv\\USD8FXMU", currency: "USD" },
  { group: "stv\\USD_NER_Std", currency: "USD" },
  { group: "stv\\USD_NER_V", currency: "USD" },
  { group: "stv\\USD_NER_VB", currency: "USD" },
  { group: "stv\\EUR_NER_Std", currency: "EUR" },
  { group: "stv\\EUR_NER_V", currency: "EUR" },
  { group: "stv\\EUR_NER_VB", currency: "EUR" },
  { group: "stv\\USD_12", currency: "USD" },
  { group: "stv\\EUR_12", currency: "EUR" },
  { group: "stv\\USD_sp", currency: "USD" },
  { group: "stv\\EUR_sp", currency: "EUR" },
  { group: "stv\\GBP_sp", currency: "GBP" },
  { group: "stv\\CAD_sp", currency: "CAD" },
  { group: "stv\\AUD_sp", currency: "AUD" },
  { group: "stv\\ZAR_sp", currency: "ZAR" },
  { group: "stv\\CZK_sp", currency: "CZK" },
  { group: "stv\\USDT_sp", currency: "UST" },
  { group: "stv\\BTC_sp", currency: "BTC" },
  { group: "stv\\ETH_sp", currency: "ETH" },
  { group: "stv\\TIO_sp", currency: "TIO" },
];

export const CTRADER_ACCOUNT_TYPES = [
  {
    name: "standard",
    label: "Standard",
    minDeposit: 50,
    minWithdrawal: 0,
  },
  {
    name: "vip",
    label: "VIP",
    minDeposit: 1000,
    minWithdrawal: 0,
  },
  {
    name: "vipblack",
    label: "VIP Black",
    minDeposit: 3000,
    minWithdrawal: 0,
  },
];

export const PLATFORMS = [
  { value: "ctrader", name: "CTrader" },
  { value: "mt5", name: "MT5" },
  // { value: "mt4", name: "MT4" },
];

export const LEVERAGE_LIVE = [50, 100, 200, 300, 400, 500];

export const LEVERAGE_DEMO = [50, 100, 200];

export const CURRENCIES = ["USD", "EUR", "GBP", "CAD", "AUD"];

export const MT5_CURRENCIES = ["USD", "EUR", "GBP", "CAD", "AUD"];
export const FRONT_END_CURRENCIES = ["USD", "EUR", "GBP", "CAD", "AUD"];
export const CRYPTO_CURRENCIES = ["BTC", "USDT", "USDC", "ETH"];
export const INNOVOULT_SUPPORTED_CURRENCIES = ["USDT", "USDC"];

export const DOCUMENTS_STATUS = {
  pending: "pending",
  approved: "approved",
  rejected: "rejected",
  not_applicable: "na",
};

export const DOCUMENTS_TYPES = {
  poi: "id_document",
  poa: "proof_of_address",
  other: "other",
};

export const PUBLIC_PATHS = [
  aLinks.index,
  aLinks.forgotPassword,
  aLinks.resetPassword,
  aLinks.verifyEmail,
  aLinks.register,
];

export const TIO_CTRADER_LIVE_ACCOUNT_TYPES = [
  {
    name: "standard",
    label: "Standard",
  },
  {
    name: "spread",
    label: "Spread",
  },
  {
    name: "spreadOnly",
    label: "Spread",
  },
  {
    name: "copyTrading",
    label: "Copy Trading",
  },
  {
    name: "vip",
    label: "VIP",
  },
  {
    name: "vipblack",
    label: "VIP Black",
  },
];

//prettier-ignore
export const USD_SYMBOLS = Object.freeze([
  "EURUSD", "GBPUSD", "USDJPY", "AUDUSD", "USDCHF", "USDCAD", "NZDUSD", "USDNOK", 
  "USDMXN", "USDSGD", "USDSEK", "USDPLN", "USDDKK", "XAUUSD", "XAGUSD", "USDTRY", 
  "USDHKD", "USDZAR", "USDHUF", "USDCZK", "USDRUB", "USDCNH", "USDRON", "USDTHB", 
  "XPDUSD", "XPTUSD", "BTCUSD", "ETHUSD", "USDTUSD", "LTCUSD", "TIOUSD",
]);

//prettier-ignore
export const FOREX_SYMBOLS = Object.freeze([
  "EURUSD", "GBPUSD", "EURJPY", "USDJPY", "AUDUSD", "USDCHF", "GBPJPY", "USDCAD", 
  "EURGBP", "EURCHF", "AUDJPY", "NZDUSD", "CHFJPY", "EURAUD", "CADJPY", "GBPAUD", 
  "EURCAD", "AUDCAD", "GBPCAD", "AUDNZD", "NZDJPY", "USDNOK", "AUDCHF", "USDMXN", 
  "GBPNZD", "EURNZD", "CADCHF", "USDSGD", "USDSEK", "NZDCAD", "EURSEK", "GBPSGD", 
  "EURNOK", "EURHUF", "USDPLN", "USDDKK", "GBPNOK", "AUDDKK", "NZDCHF", "GBPCHF", 
  "USDTRY", "EURTRY", "EURHKD", "EURZAR", "SGDJPY", "USDHKD", "USDZAR", "EURMXN", 
  "EURPLN", "GBPZAR", "NZDSGD", "USDHUF", "EURCZK", "USDCZK", "EURDKK", "EURRUB", 
  "USDRUB", "USDCNH", "GBPSEK", "GBPPLN", "AUDSEK", "AUDSGD", "AUDZAR", "CADDKK", 
  "CADHKD", "CADMXN", "CADNOK", "CADSEK", "CADSGD", "CHFNOK", "CHFPLN", "CHFSEK", 
  "CHFSGD", "CHFZAR", "DKKNOK", "DKKSEK", "EURCNH", "EURILS", "EURRON", "EURSGD", 
  "GBPDKK", "GBPTRY", "HKDJPY", "NOKJPY", "NOKSEK", "NZDSEK", "TRYJPY", "USDRON", 
  "USDTHB", "ZARJPY"
]);

export const CATEGORIES = Object.freeze({
  FOREX: "forex",
  CRYPTO: "crypto",
  INDICES: "indices",
  STOCKS: "stocks",
  COMMODITIES: "commodities",
  FUTURES: "futures",
  OTHER: "other",
});

export const FOREX_SYMBOLS_USD_CONVERSIONS = Object.freeze({
  EURJPY: "USDJPY",
  GBPJPY: "USDJPY",
  EURGBP: "GBPUSD",
  EURCHF: "USDCHF",
  AUDJPY: "USDJPY",
  CHFJPY: "USDJPY",
  EURAUD: "AUDUSD",
  CADJPY: "USDJPY",
  GBPAUD: "AUDUSD",
  EURCAD: "USDCAD",
  AUDCAD: "USDCAD",
  GBPCAD: "USDCAD",
  AUDNZD: "NZDUSD",
  NZDJPY: "USDJPY",
  AUDCHF: "USDCHF",
  GBPNZD: "NZDUSD",
  EURNZD: "NZDUSD",
  CADCHF: "USDCHF",
  NZDCAD: "USDCAD",
  EURSEK: "USDSEK",
  GBPSGD: "USDSGD",
  EURNOK: "USDNOK",
  EURHUF: "USDHUF",
  GBPNOK: "USDNOK",
  AUDDKK: "USDDKK",
  NZDCHF: "USDCHF",
  GBPCHF: "USDCHF",
  EURTRY: "USDTRY",
  EURHKD: "USDHKD",
  EURZAR: "USDZAR",
  SGDJPY: "USDJPY",
  EURMXN: "USDMXN",
  EURPLN: "USDPLN",
  GBPZAR: "USDZAR",
  NZDSGD: "USDSGD",
  EURCZK: "USDCZK",
  EURDKK: "USDDKK",
  EURRUB: "USDRUB",
  GBPSEK: "USDSEK",
  GBPPLN: "USDPLN",
  AUDSEK: "USDSEK",
  AUDSGD: "USDSGD",
  AUDZAR: "USDZAR",
  CADDKK: "USDDKK",
  CADHKD: "USDHKD",
  CADMXN: "USDMXN",
  CADNOK: "USDNOK",
  CADSEK: "USDSEK",
  CADSGD: "USDSGD",
  CHFNOK: "USDNOK",
  CHFPLN: "USDPLN",
  CHFSEK: "USDSEK",
  CHFSGD: "USDSGD",
  CHFZAR: "USDZAR",
  DKKNOK: "USDNOK",
  DKKSEK: "USDSEK",
  EURCNH: "USDCNH",
  EURILS: "EURUSD",
  EURRON: "USDRON",
  EURSGD: "USDSGD",
  GBPDKK: "USDDKK",
  GBPTRY: "USDTRY",
  HKDJPY: "USDJPY",
  NOKJPY: "USDJPY",
  NOKSEK: "USDSEK",
  NZDSEK: "USDSEK",
  TRYJPY: "USDJPY",
  ZARJPY: "USDJPY",
});
